import type { Metadata } from "next";
import {  Oswald } from "next/font/google";
import "./globals.css";
import Navber from "@/sheared/Navber";
import Footer from "@/sheared/Footer";
import FitLogProvider from "@/context/FitLogContext";
import { ToastContainer } from "react-toastify";


const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "FitLog",
  description: "Generated by create FitLog",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${oswald.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <FitLogProvider>
          <ToastContainer />

        <Navber />
        {children}

        <Footer />
        </FitLogProvider>
        </body>
    </html>
  );
}
